require('telescope').setup{
  -- defaults = {
  --   layout_strategy='vertical',
  --   layout_config = {
  --     vertical = { width = 0.8 }
  --     -- other layout configuration here
  --   },
  -- },
  -- pickers = {
  --   -- find_files = {
  --   --   theme = "dropdown",
  --   --   horizontal = "0.8",
  --   -- },
  --   -- -- live_grep = {
  --   --   theme = "dropdown",
  --   -- }
  --   --
  -- },
  -- extensions = {
  --   -- ...
  -- }
}
